Better output

diff --git a/gvirtus-test b/gvirtus-test
--- a/gvirtus-test
+++ b/gvirtus-test
@@ -14,11 +14,12 @@ if [ "$#" -eq 3 ]; then
     echo "Avoid file doesn't exist"
     exit -1
   fi
-  cp $avoid_file /tmp/avoid.txt
-  avoid_file="/tmp/avoid.txt"
+  _avoid_file="/tmp/avoid-$RANDOM-.txt"
+  cat $avoid_file | sed '/^#/ d' >$_avoid_file
 fi
 
-echo >$output_file "TYPE;SAMPLE;RESULT;ERROR"
+_output_file="/tmp/output-$RANDOM-.txt"
+echo >$_output_file "TYPE;SAMPLE;RESULT;ERROR"
 
 cd $base_dir
 sample_type_paths=`ls -d ${base_dir}/?_*`
@@ -26,6 +27,7 @@ for sample_type_path in $sample_type_paths
 do
   sample_paths=`ls -d ${sample_type_path}/*`
   sample_type=`basename $sample_type_path`
+  echo "In $sample_type_path ..."
   for sample_path in $sample_paths
   do
     sample_exec=`basename $sample_path`
@@ -33,25 +35,31 @@ do
     if [ -f "$sample_exec" ]; then
       avoid=""
       if [ -n "$avoid_file" ]; then
-        avoid=`grep -w $sample_type/$sample_exec $avoid_file`
+        avoid=`grep -w $sample_type/$sample_exec $_avoid_file`
       fi
       if [ -z "$avoid" ]; then
-        rm /tmp/err.txt
+        _stderr_file="/tmp/stderr-$RANDOM-.txt"
         echo "Testing: $sample_type/$sample_exec"
         err=""
-        ./$sample_exec >/dev/null 2>/tmp/err.txt
-        if [ $? -eq 0 ]; then
-          result="OK"
-        else
-          result="FAIL"
-          err=`head -n 1 /tmp/err.txt`
-          echo "FAIL:"
-          cat /tmp/err.txt
+        result="OK"
+        ./$sample_exec >/dev/null 2>$_stderr_file
+        if [ $? -ne 0 ]; then
+          err_lines=`cat $_stderr_file | wc | awk '{ print $1 }'`
+          skip_err_lines=`grep "no version information available" $_stderr_file | wc | awk '{ print $1 }'`
+          if [ "$err_lines" -gt "$skip_err_lines" ]; then
+            result="FAIL"
+            err=`tr '\n' ';' <$_stderr_file`
+            echo "FAIL:"
+            cat $_stderr_file
+          fi
         fi
+        rm $_stderr_file 2>/dev/null
         echo "----------------------------"
-        echo >>$output_file "$sample_type;$sample_exec;$result;$err"
+        echo >>$_output_file "$sample_type;$sample_exec;$result;$err"
       fi
     fi
   done
 done
-
+cp $_output_file $output_file
+rm $_output_file 2>/dev/null
+rm $_avoid_file 2>/dev/null
